// <auto-generated />
using System;
using HikiStudio.LearnVocabulary.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HikiStudio.LearnVocabulary.Data.Migrations
{
    [DbContext(typeof(LanguageLearningDbContext))]
    [Migration("20231031160516_CreateDB")]
    partial class CreateDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HikiStudio.LearnVocabulary.Data.Entities.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AppRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e1db1200-1bb6-4156-9da3-135e91d94aba"),
                            ConcurrencyStamp = "4d3dd428-2b33-40f0-98fa-a0ca53c56b91",
                            CreatedBy = new Guid("0b64f6f0-9f60-45c9-9e7b-f68ccc3fc57f"),
                            DateCreated = new DateTime(2023, 10, 31, 23, 5, 15, 933, DateTimeKind.Local).AddTicks(1837),
                            Description = "Administrator Role",
                            IsDeleted = false,
                            Name = "admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("c489f858-aabd-4264-96c1-5cdca251d871"),
                            ConcurrencyStamp = "5ab4d9fc-d60b-4d3b-af73-bb81bd9075cb",
                            CreatedBy = new Guid("0b64f6f0-9f60-45c9-9e7b-f68ccc3fc57f"),
                            DateCreated = new DateTime(2023, 10, 31, 23, 5, 15, 933, DateTimeKind.Local).AddTicks(1848),
                            Description = "Team Members Role",
                            IsDeleted = false,
                            Name = "teamMembers",
                            NormalizedName = "TEAMMEMBERS"
                        },
                        new
                        {
                            Id = new Guid("71b1b0a6-7eab-476c-b177-1d37e120184c"),
                            ConcurrencyStamp = "b0eae8e2-4650-4bab-849f-938e09104d17",
                            CreatedBy = new Guid("0b64f6f0-9f60-45c9-9e7b-f68ccc3fc57f"),
                            DateCreated = new DateTime(2023, 10, 31, 23, 5, 15, 933, DateTimeKind.Local).AddTicks(1851),
                            Description = "Creator Role",
                            IsDeleted = false,
                            Name = "creator",
                            NormalizedName = "CREATOR"
                        },
                        new
                        {
                            Id = new Guid("2f0c7b75-8934-4101-bef2-c850e42d21de"),
                            ConcurrencyStamp = "1dde045e-2f20-4209-922c-228917f1a04f",
                            CreatedBy = new Guid("0b64f6f0-9f60-45c9-9e7b-f68ccc3fc57f"),
                            DateCreated = new DateTime(2023, 10, 31, 23, 5, 15, 933, DateTimeKind.Local).AddTicks(1869),
                            Description = "Reader Role",
                            IsDeleted = false,
                            Name = "reader",
                            NormalizedName = "READER"
                        });
                });

            modelBuilder.Entity("HikiStudio.LearnVocabulary.Data.Entities.AppRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AppRoleClaims", (string)null);
                });

            modelBuilder.Entity("HikiStudio.LearnVocabulary.Data.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("AppUserTypeId")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatePasswordChanged")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("GenderId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCreateAppUserWithThirdParty")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("IsOTPVerified")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPasswordChanged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("OTP")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("OTPExpires")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TokenCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TokenExpires")
                        .HasColumnType("datetime2");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserImageURL")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AppUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0b64f6f0-9f60-45c9-9e7b-f68ccc3fc57f"),
                            AccessFailedCount = 0,
                            AppUserTypeId = 0,
                            ConcurrencyStamp = "1b4e3857-d120-4ad9-9ae5-a26468466236",
                            DOB = new DateTime(2001, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tranquangbdhz@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Tran",
                            GenderId = 1,
                            IsCreateAppUserWithThirdParty = false,
                            IsDeleted = false,
                            IsPasswordChanged = false,
                            LastName = "Quang",
                            LockoutEnabled = false,
                            NormalizedEmail = "TRANQUANGBDHZ@GMAIL.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAEAqhkmDy/vWD20rFdWiyuPUrJoB1ecesiHiKvSSnfPSQKgIvHrZvzCXwlm2can6QVQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserImageURL = "",
                            UserName = "quangbdhz"
                        },
                        new
                        {
                            Id = new Guid("0ae34db7-ea08-42d2-9aef-098efcdd2c1e"),
                            AccessFailedCount = 0,
                            AppUserTypeId = 0,
                            ConcurrencyStamp = "02411099-33a4-49d9-b861-deff4ee3f5e5",
                            DOB = new DateTime(2000, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DatePasswordChanged = new DateTime(2023, 10, 31, 23, 5, 15, 947, DateTimeKind.Local).AddTicks(1949),
                            Email = "hikistudio@hiki.space",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            GenderId = 2,
                            IsCreateAppUserWithThirdParty = false,
                            IsDeleted = false,
                            IsPasswordChanged = true,
                            LastName = "HikiStudio",
                            LockoutEnabled = false,
                            NormalizedEmail = "HIKISTUDIO@HIKI.SPACE",
                            NormalizedUserName = "HIKISTUDIO",
                            PasswordHash = "AQAAAAEAACcQAAAAEPuf+XwjkEFoOEBNQby8QPoHhpD+ayH+8MD4OiWW6yyXyunrJmPMGkhr5BAkYzNp0w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserImageURL = "",
                            UserName = "hikistudio"
                        },
                        new
                        {
                            Id = new Guid("3e3245cb-bc7b-4c08-ad09-72fbd736fc9a"),
                            AccessFailedCount = 0,
                            AppUserTypeId = 0,
                            ConcurrencyStamp = "079ea7f7-04c4-4da1-a186-93f301712082",
                            DOB = new DateTime(1990, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DatePasswordChanged = new DateTime(2023, 10, 31, 23, 5, 15, 954, DateTimeKind.Local).AddTicks(4486),
                            Email = "lionelmessi@hiki.space",
                            EmailConfirmed = true,
                            FirstName = "Lionel",
                            GenderId = 1,
                            IsCreateAppUserWithThirdParty = false,
                            IsDeleted = false,
                            IsPasswordChanged = true,
                            LastName = "Messi",
                            LockoutEnabled = false,
                            NormalizedEmail = "LIONELMESSI@HIKI.SPACE",
                            NormalizedUserName = "YUKINO",
                            PasswordHash = "AQAAAAEAACcQAAAAEJ8kIPFx5dd/PAAj/WcbNuuHP5OiYGCa93JRNvGB2SL7K8xBJnML2QlLgQfLbR5IbA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserImageURL = "",
                            UserName = "lionelmessi"
                        },
                        new
                        {
                            Id = new Guid("d8682aa6-255a-4b31-aeaa-1aff35a8be58"),
                            AccessFailedCount = 0,
                            AppUserTypeId = 0,
                            ConcurrencyStamp = "b9804ab0-27ca-43a9-a89d-edc9361e97e9",
                            DOB = new DateTime(2001, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DatePasswordChanged = new DateTime(2023, 10, 31, 23, 5, 15, 961, DateTimeKind.Local).AddTicks(4905),
                            Email = "creator@hiki.space",
                            EmailConfirmed = true,
                            FirstName = "Creator",
                            GenderId = 2,
                            IsCreateAppUserWithThirdParty = false,
                            IsDeleted = false,
                            IsPasswordChanged = true,
                            LastName = "HikiStudio",
                            LockoutEnabled = false,
                            NormalizedEmail = "CREATOR@HIKI.SPACE",
                            NormalizedUserName = "CREATOR",
                            PasswordHash = "AQAAAAEAACcQAAAAELaEC0a/2fhqK+zhKKe8xglhL8CTuTQiKfZThuxOgl1ZEx//n3rmH2ycWzqsEOwg0Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserImageURL = "",
                            UserName = "creator"
                        },
                        new
                        {
                            Id = new Guid("4354acbc-a32a-4a28-b865-deb49695171f"),
                            AccessFailedCount = 0,
                            AppUserTypeId = 0,
                            ConcurrencyStamp = "41f36d66-fffa-461a-9c4e-c5084b9b5940",
                            DOB = new DateTime(2001, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DatePasswordChanged = new DateTime(2023, 10, 31, 23, 5, 15, 968, DateTimeKind.Local).AddTicks(3794),
                            Email = "reader@hiki.space",
                            EmailConfirmed = true,
                            FirstName = "Reader",
                            GenderId = 3,
                            IsCreateAppUserWithThirdParty = false,
                            IsDeleted = false,
                            IsPasswordChanged = true,
                            LastName = "HikiStudio",
                            LockoutEnabled = false,
                            NormalizedEmail = "READER@HIKI.SPACE",
                            NormalizedUserName = "READER",
                            PasswordHash = "AQAAAAEAACcQAAAAEIzcO8CNBxnEcQ6JeXDXLj2MQIiZhB7sIx7xItpz5RCiWHKsF/j4z9MYwc/CJ+udTg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserImageURL = "",
                            UserName = "reader"
                        });
                });

            modelBuilder.Entity("HikiStudio.LearnVocabulary.Data.Entities.AppUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AppUserClaims", (string)null);
                });

            modelBuilder.Entity("HikiStudio.LearnVocabulary.Data.Entities.AppUserLogin", b =>
                {
                    b.Property<int>("AppUserLoginId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppUserLoginId"), 1L, 1);

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AppUserLoginId");

                    b.HasIndex("UserId");

                    b.ToTable("AppUserLogins", (string)null);
                });

            modelBuilder.Entity("HikiStudio.LearnVocabulary.Data.Entities.AppUserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppUserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValue(new Guid("00000000-0000-0000-0000-000000000000"));

                    b.HasKey("UserId", "RoleId", "AppUserRoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AppUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("0b64f6f0-9f60-45c9-9e7b-f68ccc3fc57f"),
                            RoleId = new Guid("e1db1200-1bb6-4156-9da3-135e91d94aba"),
                            AppUserRoleId = new Guid("706cec7c-8410-4070-8b8f-7f3176a2e344")
                        },
                        new
                        {
                            UserId = new Guid("0b64f6f0-9f60-45c9-9e7b-f68ccc3fc57f"),
                            RoleId = new Guid("2f0c7b75-8934-4101-bef2-c850e42d21de"),
                            AppUserRoleId = new Guid("39ae1190-1b0a-4fcd-9e3c-a101e1cc1fe0")
                        },
                        new
                        {
                            UserId = new Guid("0ae34db7-ea08-42d2-9aef-098efcdd2c1e"),
                            RoleId = new Guid("e1db1200-1bb6-4156-9da3-135e91d94aba"),
                            AppUserRoleId = new Guid("5c4c5850-7e50-48e9-ab16-a65c4c7dd2bf")
                        },
                        new
                        {
                            UserId = new Guid("0ae34db7-ea08-42d2-9aef-098efcdd2c1e"),
                            RoleId = new Guid("2f0c7b75-8934-4101-bef2-c850e42d21de"),
                            AppUserRoleId = new Guid("553a9b94-0e18-43cd-b6a8-e1142ae15dbc")
                        },
                        new
                        {
                            UserId = new Guid("3e3245cb-bc7b-4c08-ad09-72fbd736fc9a"),
                            RoleId = new Guid("c489f858-aabd-4264-96c1-5cdca251d871"),
                            AppUserRoleId = new Guid("4d57e875-7e27-4114-a00b-eb3f9b821ae4")
                        },
                        new
                        {
                            UserId = new Guid("3e3245cb-bc7b-4c08-ad09-72fbd736fc9a"),
                            RoleId = new Guid("2f0c7b75-8934-4101-bef2-c850e42d21de"),
                            AppUserRoleId = new Guid("fcee965a-d828-43d3-85a8-61417b9a20a5")
                        },
                        new
                        {
                            UserId = new Guid("d8682aa6-255a-4b31-aeaa-1aff35a8be58"),
                            RoleId = new Guid("71b1b0a6-7eab-476c-b177-1d37e120184c"),
                            AppUserRoleId = new Guid("dd725f3c-4ac0-4af4-a379-c164af4e8e30")
                        },
                        new
                        {
                            UserId = new Guid("d8682aa6-255a-4b31-aeaa-1aff35a8be58"),
                            RoleId = new Guid("2f0c7b75-8934-4101-bef2-c850e42d21de"),
                            AppUserRoleId = new Guid("c25eb131-2b43-4477-b52d-98bbb198bf99")
                        },
                        new
                        {
                            UserId = new Guid("4354acbc-a32a-4a28-b865-deb49695171f"),
                            RoleId = new Guid("2f0c7b75-8934-4101-bef2-c850e42d21de"),
                            AppUserRoleId = new Guid("4dae3bc2-0757-4061-a757-43a09f87fe30")
                        });
                });

            modelBuilder.Entity("HikiStudio.LearnVocabulary.Data.Entities.AppUserToken", b =>
                {
                    b.Property<int>("AppUserTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppUserTokenId"), 1L, 1);

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AppUserTokenId");

                    b.HasIndex("UserId");

                    b.ToTable("AppUserTokens", (string)null);
                });

            modelBuilder.Entity("HikiStudio.LearnVocabulary.Data.Entities.AudioClip", b =>
                {
                    b.Property<long>("AudioClipID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AudioClipID"), 1L, 1);

                    b.Property<string>("AudioURL")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("PronunciationTypeID")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("VocabularyWordID")
                        .HasColumnType("bigint");

                    b.HasKey("AudioClipID");

                    b.HasIndex("PronunciationTypeID");

                    b.HasIndex("VocabularyWordID");

                    b.ToTable("AudioClips", (string)null);
                });

            modelBuilder.Entity("HikiStudio.LearnVocabulary.Data.Entities.Language", b =>
                {
                    b.Property<int>("LanguageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LanguageID"), 1L, 1);

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LanguageID");

                    b.ToTable("Languages", (string)null);
                });

            modelBuilder.Entity("HikiStudio.LearnVocabulary.Data.Entities.PronunciationType", b =>
                {
                    b.Property<int>("PronunciationTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PronunciationTypeID"), 1L, 1);

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PronunciationTypeName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PronunciationTypeID");

                    b.ToTable("PronunciationTypes", (string)null);
                });

            modelBuilder.Entity("HikiStudio.LearnVocabulary.Data.Entities.VocabularyType", b =>
                {
                    b.Property<int>("VocabularyTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VocabularyTypeID"), 1L, 1);

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VocabularyTypeName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("VocabularyTypeID");

                    b.ToTable("VocabularyTypes", (string)null);
                });

            modelBuilder.Entity("HikiStudio.LearnVocabulary.Data.Entities.VocabularyWord", b =>
                {
                    b.Property<long>("VocabularyWordID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("VocabularyWordID"), 1L, 1);

                    b.Property<string>("Antonyms")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ExampleSentence")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageURL")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("LanguageID")
                        .HasColumnType("int");

                    b.Property<string>("Pronunciation")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Synonyms")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("VocabularyTypeID")
                        .HasColumnType("int");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("VocabularyWordID");

                    b.HasIndex("LanguageID");

                    b.HasIndex("VocabularyTypeID");

                    b.ToTable("VocabularyWords", (string)null);
                });

            modelBuilder.Entity("HikiStudio.LearnVocabulary.Data.Entities.AppRoleClaim", b =>
                {
                    b.HasOne("HikiStudio.LearnVocabulary.Data.Entities.AppRole", "AppRole")
                        .WithMany("AppRoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppRole");
                });

            modelBuilder.Entity("HikiStudio.LearnVocabulary.Data.Entities.AppUserClaim", b =>
                {
                    b.HasOne("HikiStudio.LearnVocabulary.Data.Entities.AppUser", "AppUser")
                        .WithMany("AppUserClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("HikiStudio.LearnVocabulary.Data.Entities.AppUserLogin", b =>
                {
                    b.HasOne("HikiStudio.LearnVocabulary.Data.Entities.AppUser", "AppUser")
                        .WithMany("AppUserLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("HikiStudio.LearnVocabulary.Data.Entities.AppUserRole", b =>
                {
                    b.HasOne("HikiStudio.LearnVocabulary.Data.Entities.AppRole", "AppRole")
                        .WithMany("AppUserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HikiStudio.LearnVocabulary.Data.Entities.AppUser", "AppUser")
                        .WithMany("AppUserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppRole");

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("HikiStudio.LearnVocabulary.Data.Entities.AppUserToken", b =>
                {
                    b.HasOne("HikiStudio.LearnVocabulary.Data.Entities.AppUser", "AppUser")
                        .WithMany("AppUserTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("HikiStudio.LearnVocabulary.Data.Entities.AudioClip", b =>
                {
                    b.HasOne("HikiStudio.LearnVocabulary.Data.Entities.PronunciationType", "PronunciationType")
                        .WithMany("AudioClips")
                        .HasForeignKey("PronunciationTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HikiStudio.LearnVocabulary.Data.Entities.VocabularyWord", "VocabularyWord")
                        .WithMany("AudioClips")
                        .HasForeignKey("VocabularyWordID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PronunciationType");

                    b.Navigation("VocabularyWord");
                });

            modelBuilder.Entity("HikiStudio.LearnVocabulary.Data.Entities.VocabularyWord", b =>
                {
                    b.HasOne("HikiStudio.LearnVocabulary.Data.Entities.Language", "Language")
                        .WithMany("VocabularyWords")
                        .HasForeignKey("LanguageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HikiStudio.LearnVocabulary.Data.Entities.VocabularyType", "VocabularyType")
                        .WithMany("VocabularyWords")
                        .HasForeignKey("VocabularyTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("VocabularyType");
                });

            modelBuilder.Entity("HikiStudio.LearnVocabulary.Data.Entities.AppRole", b =>
                {
                    b.Navigation("AppRoleClaims");

                    b.Navigation("AppUserRoles");
                });

            modelBuilder.Entity("HikiStudio.LearnVocabulary.Data.Entities.AppUser", b =>
                {
                    b.Navigation("AppUserClaims");

                    b.Navigation("AppUserLogins");

                    b.Navigation("AppUserRoles");

                    b.Navigation("AppUserTokens");
                });

            modelBuilder.Entity("HikiStudio.LearnVocabulary.Data.Entities.Language", b =>
                {
                    b.Navigation("VocabularyWords");
                });

            modelBuilder.Entity("HikiStudio.LearnVocabulary.Data.Entities.PronunciationType", b =>
                {
                    b.Navigation("AudioClips");
                });

            modelBuilder.Entity("HikiStudio.LearnVocabulary.Data.Entities.VocabularyType", b =>
                {
                    b.Navigation("VocabularyWords");
                });

            modelBuilder.Entity("HikiStudio.LearnVocabulary.Data.Entities.VocabularyWord", b =>
                {
                    b.Navigation("AudioClips");
                });
#pragma warning restore 612, 618
        }
    }
}
